### ISSUE TITLE
KeyError executing in Google Colab

### ISSUE THREAD

**Issue by lenyabloko** [simonw/csv-diff#25]
```
!csv-diff /content/antecedents.tsv /content/base/antecedents.tsv --key=id
```
Traceback (most recent call last):
  File "/usr/local/bin/csv-diff", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/csv_diff/cli.py", line 60, in cli
    diff = compare(load(previous), load(current), show_unchanged)
  File "/usr/local/lib/python3.7/dist-packages/csv_diff/cli.py", line 57, in load
    open(filename, newline=""), key=key, dialect=dialect.get(format)
  File "/usr/local/lib/python3.7/dist-packages/csv_diff/__init__.py", line 26, in load_csv
    return {keyfn(r): r for r in rows}
  File "/usr/local/lib/python3.7/dist-packages/csv_diff/__init__.py", line 26, in <dictcomp>
    return {keyfn(r): r for r in rows}
  File "/usr/local/lib/python3.7/dist-packages/csv_diff/__init__.py", line 21, in <lambda>
    keyfn = lambda r: r[key]
KeyError: 'id'

**Comment by lenyabloko** [comment]
My bad. Files had no headers.
