### ISSUE TITLE
KeyError in load_csv

### ISSUE THREAD

**Issue by dvm579** [simonw/csv-diff#26]
Hello,

I am getting a KeyError when comparing two CSV's with the following header rows, using `key='''"Event ID"'''`:

current.csv
`"","Event ID","Primary","EVENT DATE","Invoice #","5 Days Notice","Registration Links","Did the vendor provide the required staff level?","Tent, including anchoring device","Tables and chairs","Yoga mats/cots/stretchers/floor mats","Administrative supplies","Traffic control devices, if applicable","Food and fluids","Emergency supply bag (confirm with SO)","Fan, air conditioner","Mobile handwashing station","At least one sign more than 3 ft tall","Did all vendor staff arrive on time?","Was ready prior to start time?","3 EpiPens (at least 1 adult and 1 pediatric dose)","Did start on time?","Onsite entire time","Were there any avoidable patient care errors?","LNO Name","Have vendor representative enter their name","Vendor Comments","Admin Comments/Response"`

update.csv
`"","Event ID","Primary","EVENT DATE","Invoice #","5 Days Notice","Registration Links","Did the vendor provide the required staff level?","Tent, including anchoring device","Tables and chairs","Yoga mats/cots/stretchers/floor mats","Administrative supplies","Traffic control devices, if applicable","Food and fluids","Emergency supply bag (confirm with SO)","Fan, air conditioner","Mobile handwashing station","At least one sign more than 3 ft tall","Did all vendor staff arrive on time?","Was ready prior to start time?","3 EpiPens (at least 1 adult and 1 pediatric dose)","Did start on time?","Onsite entire time","Were there any avoidable patient care errors?","LNO Name","Have vendor representative enter their name","Vendor Comments","Admin Comments/Response"`

As you can see, the 2 header rows contain the same exact columns, and '"Event ID"' is present in both. However, the load_csv function is still returning: `KeyError: '"Event ID"'`

Any help would be greatly appreciated!

**Comment by dvm579** [comment]
Here is the full stacktrace of the error:

Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/dhruvamagar/PycharmProjects/IEMAFeedbackScraper/IEMAfeedbackscraper.py", line 267, in <module>
    main()
  File "/Users/dhruvamagar/PycharmProjects/IEMAFeedbackScraper/IEMAfeedbackscraper.py", line 262, in main
    test = FeedbackUpdate()
  File "/Users/dhruvamagar/PycharmProjects/IEMAFeedbackScraper/IEMAfeedbackscraper.py", line 89, in __init__
    self.__diff = compare(load_csv(open(current_csv, encoding='utf-8'), key='''"Event ID"'''),
  File "/Users/dhruvamagar/PycharmProjects/IEMAFeedbackScraper/venv/lib/python3.9/site-packages/csv_diff/__init__.py", line 26, in load_csv
    return {keyfn(r): r for r in rows}
  File "/Users/dhruvamagar/PycharmProjects/IEMAFeedbackScraper/venv/lib/python3.9/site-packages/csv_diff/__init__.py", line 26, in <dictcomp>
    return {keyfn(r): r for r in rows}
  File "/Users/dhruvamagar/PycharmProjects/IEMAFeedbackScraper/venv/lib/python3.9/site-packages/csv_diff/__init__.py", line 21, in <lambda>
    keyfn = lambda r: r[key]
KeyError: '"Event ID"'
python-BaseException

**Comment by dvm579** [comment]
I just figured it out, I had to add `dialect="excel"`

These csv files are being generated by pandas.to_csv with no additional parameters, if that is useful for anybody.
